export const UPDATE_TVL = 'updateTVL'
export const UPDATE_APY = 'updateAPY'
export const UPDATE_DEPOSITED = 'updateDeposited'
export const OPEN_MODAL = 'openModal'
export const SORT_BY_TVL = 'sortByTVL'
export const SORT_BY_APY = 'sortByApy'
export const SORT_BY_DEPOSITED = 'sortByDeposited'
